//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ControlDeEstudio.TestServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.DTOs")]
    public partial class CategoriaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CategoriaIdField;
        
        private string ErrorField;
        
        private string EstadoField;
        
        private string NombreField;
        
        private System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.TemasDTO> TemasField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.TemasDTO> Temas {
            get {
                return this.TemasField;
            }
            set {
                if ((object.ReferenceEquals(this.TemasField, value) != true)) {
                    this.TemasField = value;
                    this.RaisePropertyChanged("Temas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemasDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.DTOs")]
    public partial class TemasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CategoriaIdField;
        
        private string ErrorField;
        
        private string EstadoField;
        
        private string NombreField;
        
        private System.Nullable<int> OrdenField;
        
        private System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.SubtemaDTO> SubTemasField;
        
        private string TemaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoriaId {
            get {
                return this.CategoriaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriaIdField, value) != true)) {
                    this.CategoriaIdField = value;
                    this.RaisePropertyChanged("CategoriaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.SubtemaDTO> SubTemas {
            get {
                return this.SubTemasField;
            }
            set {
                if ((object.ReferenceEquals(this.SubTemasField, value) != true)) {
                    this.SubTemasField = value;
                    this.RaisePropertyChanged("SubTemas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemaId {
            get {
                return this.TemaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaIdField, value) != true)) {
                    this.TemaIdField = value;
                    this.RaisePropertyChanged("TemaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubtemaDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.DTOs")]
    public partial class SubtemaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string DescripcionField;
        
        private string EstadoField;
        
        private int OrdenField;
        
        private System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.ReferenciaDTO> ReferenciasField;
        
        private string SubtemaIdField;
        
        private string TemaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.ReferenciaDTO> Referencias {
            get {
                return this.ReferenciasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciasField, value) != true)) {
                    this.ReferenciasField = value;
                    this.RaisePropertyChanged("Referencias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtemaId {
            get {
                return this.SubtemaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtemaIdField, value) != true)) {
                    this.SubtemaIdField = value;
                    this.RaisePropertyChanged("SubtemaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemaId {
            get {
                return this.TemaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TemaIdField, value) != true)) {
                    this.TemaIdField = value;
                    this.RaisePropertyChanged("TemaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenciaDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.DTOs")]
    public partial class ReferenciaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AutorField;
        
        private string DescripcionField;
        
        private string FuenteField;
        
        private int ReferenciaIdField;
        
        private string SubtemaIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor {
            get {
                return this.AutorField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorField, value) != true)) {
                    this.AutorField = value;
                    this.RaisePropertyChanged("Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fuente {
            get {
                return this.FuenteField;
            }
            set {
                if ((object.ReferenceEquals(this.FuenteField, value) != true)) {
                    this.FuenteField = value;
                    this.RaisePropertyChanged("Fuente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReferenciaId {
            get {
                return this.ReferenciaIdField;
            }
            set {
                if ((this.ReferenciaIdField.Equals(value) != true)) {
                    this.ReferenciaIdField = value;
                    this.RaisePropertyChanged("ReferenciaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubtemaId {
            get {
                return this.SubtemaIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubtemaIdField, value) != true)) {
                    this.SubtemaIdField = value;
                    this.RaisePropertyChanged("SubtemaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestServiceReference.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/DoWork", ReplyAction="http://tempuri.org/ITestService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/ObtenerCategorias", ReplyAction="http://tempuri.org/ITestService/ObtenerCategoriasResponse")]
        System.IAsyncResult BeginObtenerCategorias(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> EndObtenerCategorias(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/AgregarCategoria", ReplyAction="http://tempuri.org/ITestService/AgregarCategoriaResponse")]
        System.IAsyncResult BeginAgregarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO, System.AsyncCallback callback, object asyncState);
        
        string EndAgregarCategoria(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EliminarCategoria", ReplyAction="http://tempuri.org/ITestService/EliminarCategoriaResponse")]
        System.IAsyncResult BeginEliminarCategoria(string Id, System.AsyncCallback callback, object asyncState);
        
        string EndEliminarCategoria(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/ModificarCategoria", ReplyAction="http://tempuri.org/ITestService/ModificarCategoriaResponse")]
        System.IAsyncResult BeginModificarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO dto, System.AsyncCallback callback, object asyncState);
        
        string EndModificarCategoria(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/GuardarTema", ReplyAction="http://tempuri.org/ITestService/GuardarTemaResponse")]
        System.IAsyncResult BeginGuardarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndGuardarTema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EliminarTema", ReplyAction="http://tempuri.org/ITestService/EliminarTemaResponse")]
        System.IAsyncResult BeginEliminarTema(string Id, System.AsyncCallback callback, object asyncState);
        
        void EndEliminarTema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EditarTema", ReplyAction="http://tempuri.org/ITestService/EditarTemaResponse")]
        System.IAsyncResult BeginEditarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndEditarTema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/GuardarSubtema", ReplyAction="http://tempuri.org/ITestService/GuardarSubtemaResponse")]
        System.IAsyncResult BeginGuardarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndGuardarSubtema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EliminarSubtema", ReplyAction="http://tempuri.org/ITestService/EliminarSubtemaResponse")]
        System.IAsyncResult BeginEliminarSubtema(string Id, System.AsyncCallback callback, object asyncState);
        
        void EndEliminarSubtema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EditarSubtema", ReplyAction="http://tempuri.org/ITestService/EditarSubtemaResponse")]
        System.IAsyncResult BeginEditarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndEditarSubtema(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/GuardarReferencia", ReplyAction="http://tempuri.org/ITestService/GuardarReferenciaResponse")]
        System.IAsyncResult BeginGuardarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndGuardarReferencia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EliminarReferencia", ReplyAction="http://tempuri.org/ITestService/EliminarReferenciaResponse")]
        System.IAsyncResult BeginEliminarReferencia(int Id, System.AsyncCallback callback, object asyncState);
        
        void EndEliminarReferencia(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ITestService/EditarReferencia", ReplyAction="http://tempuri.org/ITestService/EditarReferenciaResponse")]
        System.IAsyncResult BeginEditarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState);
        
        void EndEditarReferencia(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : ControlDeEstudio.TestServiceReference.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerCategoriasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerCategoriasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgregarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AgregarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EliminarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EliminarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModificarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ModificarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<ControlDeEstudio.TestServiceReference.ITestService>, ControlDeEstudio.TestServiceReference.ITestService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerCategoriasDelegate;
        
        private EndOperationDelegate onEndObtenerCategoriasDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerCategoriasCompletedDelegate;
        
        private BeginOperationDelegate onBeginAgregarCategoriaDelegate;
        
        private EndOperationDelegate onEndAgregarCategoriaDelegate;
        
        private System.Threading.SendOrPostCallback onAgregarCategoriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarCategoriaDelegate;
        
        private EndOperationDelegate onEndEliminarCategoriaDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarCategoriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginModificarCategoriaDelegate;
        
        private EndOperationDelegate onEndModificarCategoriaDelegate;
        
        private System.Threading.SendOrPostCallback onModificarCategoriaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGuardarTemaDelegate;
        
        private EndOperationDelegate onEndGuardarTemaDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarTemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarTemaDelegate;
        
        private EndOperationDelegate onEndEliminarTemaDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarTemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditarTemaDelegate;
        
        private EndOperationDelegate onEndEditarTemaDelegate;
        
        private System.Threading.SendOrPostCallback onEditarTemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGuardarSubtemaDelegate;
        
        private EndOperationDelegate onEndGuardarSubtemaDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarSubtemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarSubtemaDelegate;
        
        private EndOperationDelegate onEndEliminarSubtemaDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarSubtemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditarSubtemaDelegate;
        
        private EndOperationDelegate onEndEditarSubtemaDelegate;
        
        private System.Threading.SendOrPostCallback onEditarSubtemaCompletedDelegate;
        
        private BeginOperationDelegate onBeginGuardarReferenciaDelegate;
        
        private EndOperationDelegate onEndGuardarReferenciaDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarReferenciaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarReferenciaDelegate;
        
        private EndOperationDelegate onEndEliminarReferenciaDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarReferenciaCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditarReferenciaDelegate;
        
        private EndOperationDelegate onEndEditarReferenciaDelegate;
        
        private System.Threading.SendOrPostCallback onEditarReferenciaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<ObtenerCategoriasCompletedEventArgs> ObtenerCategoriasCompleted;
        
        public event System.EventHandler<AgregarCategoriaCompletedEventArgs> AgregarCategoriaCompleted;
        
        public event System.EventHandler<EliminarCategoriaCompletedEventArgs> EliminarCategoriaCompleted;
        
        public event System.EventHandler<ModificarCategoriaCompletedEventArgs> ModificarCategoriaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> GuardarTemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EliminarTemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditarTemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> GuardarSubtemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EliminarSubtemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditarSubtemaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> GuardarReferenciaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EliminarReferenciaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EditarReferenciaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginObtenerCategorias(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerCategorias(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> ControlDeEstudio.TestServiceReference.ITestService.EndObtenerCategorias(System.IAsyncResult result) {
            return base.Channel.EndObtenerCategorias(result);
        }
        
        private System.IAsyncResult OnBeginObtenerCategorias(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginObtenerCategorias(callback, asyncState);
        }
        
        private object[] OnEndObtenerCategorias(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> retVal = ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndObtenerCategorias(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerCategoriasCompleted(object state) {
            if ((this.ObtenerCategoriasCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerCategoriasCompleted(this, new ObtenerCategoriasCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerCategoriasAsync() {
            this.ObtenerCategoriasAsync(null);
        }
        
        public void ObtenerCategoriasAsync(object userState) {
            if ((this.onBeginObtenerCategoriasDelegate == null)) {
                this.onBeginObtenerCategoriasDelegate = new BeginOperationDelegate(this.OnBeginObtenerCategorias);
            }
            if ((this.onEndObtenerCategoriasDelegate == null)) {
                this.onEndObtenerCategoriasDelegate = new EndOperationDelegate(this.OnEndObtenerCategorias);
            }
            if ((this.onObtenerCategoriasCompletedDelegate == null)) {
                this.onObtenerCategoriasCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerCategoriasCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerCategoriasDelegate, null, this.onEndObtenerCategoriasDelegate, this.onObtenerCategoriasCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginAgregarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAgregarCategoria(categoriaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ControlDeEstudio.TestServiceReference.ITestService.EndAgregarCategoria(System.IAsyncResult result) {
            return base.Channel.EndAgregarCategoria(result);
        }
        
        private System.IAsyncResult OnBeginAgregarCategoria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO = ((ControlDeEstudio.TestServiceReference.CategoriaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginAgregarCategoria(categoriaDTO, callback, asyncState);
        }
        
        private object[] OnEndAgregarCategoria(System.IAsyncResult result) {
            string retVal = ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndAgregarCategoria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAgregarCategoriaCompleted(object state) {
            if ((this.AgregarCategoriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AgregarCategoriaCompleted(this, new AgregarCategoriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AgregarCategoriaAsync(ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO) {
            this.AgregarCategoriaAsync(categoriaDTO, null);
        }
        
        public void AgregarCategoriaAsync(ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO, object userState) {
            if ((this.onBeginAgregarCategoriaDelegate == null)) {
                this.onBeginAgregarCategoriaDelegate = new BeginOperationDelegate(this.OnBeginAgregarCategoria);
            }
            if ((this.onEndAgregarCategoriaDelegate == null)) {
                this.onEndAgregarCategoriaDelegate = new EndOperationDelegate(this.OnEndAgregarCategoria);
            }
            if ((this.onAgregarCategoriaCompletedDelegate == null)) {
                this.onAgregarCategoriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAgregarCategoriaCompleted);
            }
            base.InvokeAsync(this.onBeginAgregarCategoriaDelegate, new object[] {
                        categoriaDTO}, this.onEndAgregarCategoriaDelegate, this.onAgregarCategoriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEliminarCategoria(string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarCategoria(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ControlDeEstudio.TestServiceReference.ITestService.EndEliminarCategoria(System.IAsyncResult result) {
            return base.Channel.EndEliminarCategoria(result);
        }
        
        private System.IAsyncResult OnBeginEliminarCategoria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id = ((string)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEliminarCategoria(Id, callback, asyncState);
        }
        
        private object[] OnEndEliminarCategoria(System.IAsyncResult result) {
            string retVal = ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEliminarCategoria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEliminarCategoriaCompleted(object state) {
            if ((this.EliminarCategoriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarCategoriaCompleted(this, new EliminarCategoriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarCategoriaAsync(string Id) {
            this.EliminarCategoriaAsync(Id, null);
        }
        
        public void EliminarCategoriaAsync(string Id, object userState) {
            if ((this.onBeginEliminarCategoriaDelegate == null)) {
                this.onBeginEliminarCategoriaDelegate = new BeginOperationDelegate(this.OnBeginEliminarCategoria);
            }
            if ((this.onEndEliminarCategoriaDelegate == null)) {
                this.onEndEliminarCategoriaDelegate = new EndOperationDelegate(this.OnEndEliminarCategoria);
            }
            if ((this.onEliminarCategoriaCompletedDelegate == null)) {
                this.onEliminarCategoriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarCategoriaCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarCategoriaDelegate, new object[] {
                        Id}, this.onEndEliminarCategoriaDelegate, this.onEliminarCategoriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginModificarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO dto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginModificarCategoria(dto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string ControlDeEstudio.TestServiceReference.ITestService.EndModificarCategoria(System.IAsyncResult result) {
            return base.Channel.EndModificarCategoria(result);
        }
        
        private System.IAsyncResult OnBeginModificarCategoria(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.CategoriaDTO dto = ((ControlDeEstudio.TestServiceReference.CategoriaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginModificarCategoria(dto, callback, asyncState);
        }
        
        private object[] OnEndModificarCategoria(System.IAsyncResult result) {
            string retVal = ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndModificarCategoria(result);
            return new object[] {
                    retVal};
        }
        
        private void OnModificarCategoriaCompleted(object state) {
            if ((this.ModificarCategoriaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ModificarCategoriaCompleted(this, new ModificarCategoriaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ModificarCategoriaAsync(ControlDeEstudio.TestServiceReference.CategoriaDTO dto) {
            this.ModificarCategoriaAsync(dto, null);
        }
        
        public void ModificarCategoriaAsync(ControlDeEstudio.TestServiceReference.CategoriaDTO dto, object userState) {
            if ((this.onBeginModificarCategoriaDelegate == null)) {
                this.onBeginModificarCategoriaDelegate = new BeginOperationDelegate(this.OnBeginModificarCategoria);
            }
            if ((this.onEndModificarCategoriaDelegate == null)) {
                this.onEndModificarCategoriaDelegate = new EndOperationDelegate(this.OnEndModificarCategoria);
            }
            if ((this.onModificarCategoriaCompletedDelegate == null)) {
                this.onModificarCategoriaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnModificarCategoriaCompleted);
            }
            base.InvokeAsync(this.onBeginModificarCategoriaDelegate, new object[] {
                        dto}, this.onEndModificarCategoriaDelegate, this.onModificarCategoriaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginGuardarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarTema(temaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndGuardarTema(System.IAsyncResult result) {
            base.Channel.EndGuardarTema(result);
        }
        
        private System.IAsyncResult OnBeginGuardarTema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.TemasDTO temaDTO = ((ControlDeEstudio.TestServiceReference.TemasDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginGuardarTema(temaDTO, callback, asyncState);
        }
        
        private object[] OnEndGuardarTema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndGuardarTema(result);
            return null;
        }
        
        private void OnGuardarTemaCompleted(object state) {
            if ((this.GuardarTemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarTemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarTemaAsync(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO) {
            this.GuardarTemaAsync(temaDTO, null);
        }
        
        public void GuardarTemaAsync(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, object userState) {
            if ((this.onBeginGuardarTemaDelegate == null)) {
                this.onBeginGuardarTemaDelegate = new BeginOperationDelegate(this.OnBeginGuardarTema);
            }
            if ((this.onEndGuardarTemaDelegate == null)) {
                this.onEndGuardarTemaDelegate = new EndOperationDelegate(this.OnEndGuardarTema);
            }
            if ((this.onGuardarTemaCompletedDelegate == null)) {
                this.onGuardarTemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarTemaCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarTemaDelegate, new object[] {
                        temaDTO}, this.onEndGuardarTemaDelegate, this.onGuardarTemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEliminarTema(string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarTema(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEliminarTema(System.IAsyncResult result) {
            base.Channel.EndEliminarTema(result);
        }
        
        private System.IAsyncResult OnBeginEliminarTema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id = ((string)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEliminarTema(Id, callback, asyncState);
        }
        
        private object[] OnEndEliminarTema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEliminarTema(result);
            return null;
        }
        
        private void OnEliminarTemaCompleted(object state) {
            if ((this.EliminarTemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarTemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarTemaAsync(string Id) {
            this.EliminarTemaAsync(Id, null);
        }
        
        public void EliminarTemaAsync(string Id, object userState) {
            if ((this.onBeginEliminarTemaDelegate == null)) {
                this.onBeginEliminarTemaDelegate = new BeginOperationDelegate(this.OnBeginEliminarTema);
            }
            if ((this.onEndEliminarTemaDelegate == null)) {
                this.onEndEliminarTemaDelegate = new EndOperationDelegate(this.OnEndEliminarTema);
            }
            if ((this.onEliminarTemaCompletedDelegate == null)) {
                this.onEliminarTemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarTemaCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarTemaDelegate, new object[] {
                        Id}, this.onEndEliminarTemaDelegate, this.onEliminarTemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEditarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditarTema(temaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEditarTema(System.IAsyncResult result) {
            base.Channel.EndEditarTema(result);
        }
        
        private System.IAsyncResult OnBeginEditarTema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.TemasDTO temaDTO = ((ControlDeEstudio.TestServiceReference.TemasDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEditarTema(temaDTO, callback, asyncState);
        }
        
        private object[] OnEndEditarTema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEditarTema(result);
            return null;
        }
        
        private void OnEditarTemaCompleted(object state) {
            if ((this.EditarTemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditarTemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditarTemaAsync(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO) {
            this.EditarTemaAsync(temaDTO, null);
        }
        
        public void EditarTemaAsync(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, object userState) {
            if ((this.onBeginEditarTemaDelegate == null)) {
                this.onBeginEditarTemaDelegate = new BeginOperationDelegate(this.OnBeginEditarTema);
            }
            if ((this.onEndEditarTemaDelegate == null)) {
                this.onEndEditarTemaDelegate = new EndOperationDelegate(this.OnEndEditarTema);
            }
            if ((this.onEditarTemaCompletedDelegate == null)) {
                this.onEditarTemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditarTemaCompleted);
            }
            base.InvokeAsync(this.onBeginEditarTemaDelegate, new object[] {
                        temaDTO}, this.onEndEditarTemaDelegate, this.onEditarTemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginGuardarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarSubtema(temaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndGuardarSubtema(System.IAsyncResult result) {
            base.Channel.EndGuardarSubtema(result);
        }
        
        private System.IAsyncResult OnBeginGuardarSubtema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO = ((ControlDeEstudio.TestServiceReference.SubtemaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginGuardarSubtema(temaDTO, callback, asyncState);
        }
        
        private object[] OnEndGuardarSubtema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndGuardarSubtema(result);
            return null;
        }
        
        private void OnGuardarSubtemaCompleted(object state) {
            if ((this.GuardarSubtemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarSubtemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarSubtemaAsync(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO) {
            this.GuardarSubtemaAsync(temaDTO, null);
        }
        
        public void GuardarSubtemaAsync(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, object userState) {
            if ((this.onBeginGuardarSubtemaDelegate == null)) {
                this.onBeginGuardarSubtemaDelegate = new BeginOperationDelegate(this.OnBeginGuardarSubtema);
            }
            if ((this.onEndGuardarSubtemaDelegate == null)) {
                this.onEndGuardarSubtemaDelegate = new EndOperationDelegate(this.OnEndGuardarSubtema);
            }
            if ((this.onGuardarSubtemaCompletedDelegate == null)) {
                this.onGuardarSubtemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarSubtemaCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarSubtemaDelegate, new object[] {
                        temaDTO}, this.onEndGuardarSubtemaDelegate, this.onGuardarSubtemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEliminarSubtema(string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarSubtema(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEliminarSubtema(System.IAsyncResult result) {
            base.Channel.EndEliminarSubtema(result);
        }
        
        private System.IAsyncResult OnBeginEliminarSubtema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id = ((string)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEliminarSubtema(Id, callback, asyncState);
        }
        
        private object[] OnEndEliminarSubtema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEliminarSubtema(result);
            return null;
        }
        
        private void OnEliminarSubtemaCompleted(object state) {
            if ((this.EliminarSubtemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarSubtemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarSubtemaAsync(string Id) {
            this.EliminarSubtemaAsync(Id, null);
        }
        
        public void EliminarSubtemaAsync(string Id, object userState) {
            if ((this.onBeginEliminarSubtemaDelegate == null)) {
                this.onBeginEliminarSubtemaDelegate = new BeginOperationDelegate(this.OnBeginEliminarSubtema);
            }
            if ((this.onEndEliminarSubtemaDelegate == null)) {
                this.onEndEliminarSubtemaDelegate = new EndOperationDelegate(this.OnEndEliminarSubtema);
            }
            if ((this.onEliminarSubtemaCompletedDelegate == null)) {
                this.onEliminarSubtemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarSubtemaCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarSubtemaDelegate, new object[] {
                        Id}, this.onEndEliminarSubtemaDelegate, this.onEliminarSubtemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEditarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditarSubtema(temaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEditarSubtema(System.IAsyncResult result) {
            base.Channel.EndEditarSubtema(result);
        }
        
        private System.IAsyncResult OnBeginEditarSubtema(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO = ((ControlDeEstudio.TestServiceReference.SubtemaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEditarSubtema(temaDTO, callback, asyncState);
        }
        
        private object[] OnEndEditarSubtema(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEditarSubtema(result);
            return null;
        }
        
        private void OnEditarSubtemaCompleted(object state) {
            if ((this.EditarSubtemaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditarSubtemaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditarSubtemaAsync(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO) {
            this.EditarSubtemaAsync(temaDTO, null);
        }
        
        public void EditarSubtemaAsync(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, object userState) {
            if ((this.onBeginEditarSubtemaDelegate == null)) {
                this.onBeginEditarSubtemaDelegate = new BeginOperationDelegate(this.OnBeginEditarSubtema);
            }
            if ((this.onEndEditarSubtemaDelegate == null)) {
                this.onEndEditarSubtemaDelegate = new EndOperationDelegate(this.OnEndEditarSubtema);
            }
            if ((this.onEditarSubtemaCompletedDelegate == null)) {
                this.onEditarSubtemaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditarSubtemaCompleted);
            }
            base.InvokeAsync(this.onBeginEditarSubtemaDelegate, new object[] {
                        temaDTO}, this.onEndEditarSubtemaDelegate, this.onEditarSubtemaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginGuardarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarReferencia(referenciaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndGuardarReferencia(System.IAsyncResult result) {
            base.Channel.EndGuardarReferencia(result);
        }
        
        private System.IAsyncResult OnBeginGuardarReferencia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO = ((ControlDeEstudio.TestServiceReference.ReferenciaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginGuardarReferencia(referenciaDTO, callback, asyncState);
        }
        
        private object[] OnEndGuardarReferencia(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndGuardarReferencia(result);
            return null;
        }
        
        private void OnGuardarReferenciaCompleted(object state) {
            if ((this.GuardarReferenciaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarReferenciaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarReferenciaAsync(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO) {
            this.GuardarReferenciaAsync(referenciaDTO, null);
        }
        
        public void GuardarReferenciaAsync(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, object userState) {
            if ((this.onBeginGuardarReferenciaDelegate == null)) {
                this.onBeginGuardarReferenciaDelegate = new BeginOperationDelegate(this.OnBeginGuardarReferencia);
            }
            if ((this.onEndGuardarReferenciaDelegate == null)) {
                this.onEndGuardarReferenciaDelegate = new EndOperationDelegate(this.OnEndGuardarReferencia);
            }
            if ((this.onGuardarReferenciaCompletedDelegate == null)) {
                this.onGuardarReferenciaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarReferenciaCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarReferenciaDelegate, new object[] {
                        referenciaDTO}, this.onEndGuardarReferenciaDelegate, this.onGuardarReferenciaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEliminarReferencia(int Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarReferencia(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEliminarReferencia(System.IAsyncResult result) {
            base.Channel.EndEliminarReferencia(result);
        }
        
        private System.IAsyncResult OnBeginEliminarReferencia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEliminarReferencia(Id, callback, asyncState);
        }
        
        private object[] OnEndEliminarReferencia(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEliminarReferencia(result);
            return null;
        }
        
        private void OnEliminarReferenciaCompleted(object state) {
            if ((this.EliminarReferenciaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarReferenciaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarReferenciaAsync(int Id) {
            this.EliminarReferenciaAsync(Id, null);
        }
        
        public void EliminarReferenciaAsync(int Id, object userState) {
            if ((this.onBeginEliminarReferenciaDelegate == null)) {
                this.onBeginEliminarReferenciaDelegate = new BeginOperationDelegate(this.OnBeginEliminarReferencia);
            }
            if ((this.onEndEliminarReferenciaDelegate == null)) {
                this.onEndEliminarReferenciaDelegate = new EndOperationDelegate(this.OnEndEliminarReferencia);
            }
            if ((this.onEliminarReferenciaCompletedDelegate == null)) {
                this.onEliminarReferenciaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarReferenciaCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarReferenciaDelegate, new object[] {
                        Id}, this.onEndEliminarReferenciaDelegate, this.onEliminarReferenciaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.TestServiceReference.ITestService.BeginEditarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditarReferencia(referenciaDTO, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.TestServiceReference.ITestService.EndEditarReferencia(System.IAsyncResult result) {
            base.Channel.EndEditarReferencia(result);
        }
        
        private System.IAsyncResult OnBeginEditarReferencia(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO = ((ControlDeEstudio.TestServiceReference.ReferenciaDTO)(inValues[0]));
            return ((ControlDeEstudio.TestServiceReference.ITestService)(this)).BeginEditarReferencia(referenciaDTO, callback, asyncState);
        }
        
        private object[] OnEndEditarReferencia(System.IAsyncResult result) {
            ((ControlDeEstudio.TestServiceReference.ITestService)(this)).EndEditarReferencia(result);
            return null;
        }
        
        private void OnEditarReferenciaCompleted(object state) {
            if ((this.EditarReferenciaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditarReferenciaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditarReferenciaAsync(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO) {
            this.EditarReferenciaAsync(referenciaDTO, null);
        }
        
        public void EditarReferenciaAsync(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, object userState) {
            if ((this.onBeginEditarReferenciaDelegate == null)) {
                this.onBeginEditarReferenciaDelegate = new BeginOperationDelegate(this.OnBeginEditarReferencia);
            }
            if ((this.onEndEditarReferenciaDelegate == null)) {
                this.onEndEditarReferenciaDelegate = new EndOperationDelegate(this.OnEndEditarReferencia);
            }
            if ((this.onEditarReferenciaCompletedDelegate == null)) {
                this.onEditarReferenciaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditarReferenciaCompleted);
            }
            base.InvokeAsync(this.onBeginEditarReferenciaDelegate, new object[] {
                        referenciaDTO}, this.onEndEditarReferenciaDelegate, this.onEditarReferenciaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ControlDeEstudio.TestServiceReference.ITestService CreateChannel() {
            return new TestServiceClientChannel(this);
        }
        
        private class TestServiceClientChannel : ChannelBase<ControlDeEstudio.TestServiceReference.ITestService>, ControlDeEstudio.TestServiceReference.ITestService {
            
            public TestServiceClientChannel(System.ServiceModel.ClientBase<ControlDeEstudio.TestServiceReference.ITestService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginObtenerCategorias(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ObtenerCategorias", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> EndObtenerCategorias(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.TestServiceReference.CategoriaDTO>)(base.EndInvoke("ObtenerCategorias", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAgregarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO categoriaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = categoriaDTO;
                System.IAsyncResult _result = base.BeginInvoke("AgregarCategoria", _args, callback, asyncState);
                return _result;
            }
            
            public string EndAgregarCategoria(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("AgregarCategoria", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEliminarCategoria(string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("EliminarCategoria", _args, callback, asyncState);
                return _result;
            }
            
            public string EndEliminarCategoria(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("EliminarCategoria", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginModificarCategoria(ControlDeEstudio.TestServiceReference.CategoriaDTO dto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = dto;
                System.IAsyncResult _result = base.BeginInvoke("ModificarCategoria", _args, callback, asyncState);
                return _result;
            }
            
            public string EndModificarCategoria(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("ModificarCategoria", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGuardarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = temaDTO;
                System.IAsyncResult _result = base.BeginInvoke("GuardarTema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGuardarTema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("GuardarTema", _args, result);
            }
            
            public System.IAsyncResult BeginEliminarTema(string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("EliminarTema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEliminarTema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EliminarTema", _args, result);
            }
            
            public System.IAsyncResult BeginEditarTema(ControlDeEstudio.TestServiceReference.TemasDTO temaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = temaDTO;
                System.IAsyncResult _result = base.BeginInvoke("EditarTema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEditarTema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EditarTema", _args, result);
            }
            
            public System.IAsyncResult BeginGuardarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = temaDTO;
                System.IAsyncResult _result = base.BeginInvoke("GuardarSubtema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGuardarSubtema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("GuardarSubtema", _args, result);
            }
            
            public System.IAsyncResult BeginEliminarSubtema(string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("EliminarSubtema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEliminarSubtema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EliminarSubtema", _args, result);
            }
            
            public System.IAsyncResult BeginEditarSubtema(ControlDeEstudio.TestServiceReference.SubtemaDTO temaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = temaDTO;
                System.IAsyncResult _result = base.BeginInvoke("EditarSubtema", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEditarSubtema(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EditarSubtema", _args, result);
            }
            
            public System.IAsyncResult BeginGuardarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = referenciaDTO;
                System.IAsyncResult _result = base.BeginInvoke("GuardarReferencia", _args, callback, asyncState);
                return _result;
            }
            
            public void EndGuardarReferencia(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("GuardarReferencia", _args, result);
            }
            
            public System.IAsyncResult BeginEliminarReferencia(int Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("EliminarReferencia", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEliminarReferencia(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EliminarReferencia", _args, result);
            }
            
            public System.IAsyncResult BeginEditarReferencia(ControlDeEstudio.TestServiceReference.ReferenciaDTO referenciaDTO, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = referenciaDTO;
                System.IAsyncResult _result = base.BeginInvoke("EditarReferencia", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEditarReferencia(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EditarReferencia", _args, result);
            }
        }
    }
}
