//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ControlDeEstudio.UsuariosServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosDTO", Namespace="http://schemas.datacontract.org/2004/07/Services.DTOs")]
    public partial class UsuariosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AreaField;
        
        private string ErrorField;
        
        private string NombreField;
        
        private string UsuarioIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioIdField, value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsuariosServiceReference.IUsuarioService")]
    public interface IUsuarioService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUsuarioService/DoWork", ReplyAction="http://tempuri.org/IUsuarioService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUsuarioService/GuardarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/GuardarUsuarioResponse")]
        System.IAsyncResult BeginGuardarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState);
        
        ControlDeEstudio.UsuariosServiceReference.UsuariosDTO EndGuardarUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUsuarioService/EditarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EditarUsuarioResponse")]
        System.IAsyncResult BeginEditarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState);
        
        ControlDeEstudio.UsuariosServiceReference.UsuariosDTO EndEditarUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUsuarioService/EliminarUsuario", ReplyAction="http://tempuri.org/IUsuarioService/EliminarUsuarioResponse")]
        System.IAsyncResult BeginEliminarUsuario(string Id, System.AsyncCallback callback, object asyncState);
        
        void EndEliminarUsuario(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IUsuarioService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IUsuarioService/ObtenerUsuariosResponse")]
        System.IAsyncResult BeginObtenerUsuarios(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> EndObtenerUsuarios(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServiceChannel : ControlDeEstudio.UsuariosServiceReference.IUsuarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GuardarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GuardarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ControlDeEstudio.UsuariosServiceReference.UsuariosDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EditarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ControlDeEstudio.UsuariosServiceReference.UsuariosDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObtenerUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ObtenerUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServiceClient : System.ServiceModel.ClientBase<ControlDeEstudio.UsuariosServiceReference.IUsuarioService>, ControlDeEstudio.UsuariosServiceReference.IUsuarioService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBeginGuardarUsuarioDelegate;
        
        private EndOperationDelegate onEndGuardarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onGuardarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditarUsuarioDelegate;
        
        private EndOperationDelegate onEndEditarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onEditarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginEliminarUsuarioDelegate;
        
        private EndOperationDelegate onEndEliminarUsuarioDelegate;
        
        private System.Threading.SendOrPostCallback onEliminarUsuarioCompletedDelegate;
        
        private BeginOperationDelegate onBeginObtenerUsuariosDelegate;
        
        private EndOperationDelegate onEndObtenerUsuariosDelegate;
        
        private System.Threading.SendOrPostCallback onObtenerUsuariosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public UsuarioServiceClient() {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<GuardarUsuarioCompletedEventArgs> GuardarUsuarioCompleted;
        
        public event System.EventHandler<EditarUsuarioCompletedEventArgs> EditarUsuarioCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> EliminarUsuarioCompleted;
        
        public event System.EventHandler<ObtenerUsuariosCompletedEventArgs> ObtenerUsuariosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.UsuariosServiceReference.IUsuarioService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.UsuariosServiceReference.IUsuarioService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.UsuariosServiceReference.IUsuarioService.BeginGuardarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGuardarUsuario(usuarioDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlDeEstudio.UsuariosServiceReference.UsuariosDTO ControlDeEstudio.UsuariosServiceReference.IUsuarioService.EndGuardarUsuario(System.IAsyncResult result) {
            return base.Channel.EndGuardarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginGuardarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto = ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(inValues[0]));
            return ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).BeginGuardarUsuario(usuarioDto, callback, asyncState);
        }
        
        private object[] OnEndGuardarUsuario(System.IAsyncResult result) {
            ControlDeEstudio.UsuariosServiceReference.UsuariosDTO retVal = ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).EndGuardarUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGuardarUsuarioCompleted(object state) {
            if ((this.GuardarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GuardarUsuarioCompleted(this, new GuardarUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GuardarUsuarioAsync(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto) {
            this.GuardarUsuarioAsync(usuarioDto, null);
        }
        
        public void GuardarUsuarioAsync(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, object userState) {
            if ((this.onBeginGuardarUsuarioDelegate == null)) {
                this.onBeginGuardarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginGuardarUsuario);
            }
            if ((this.onEndGuardarUsuarioDelegate == null)) {
                this.onEndGuardarUsuarioDelegate = new EndOperationDelegate(this.OnEndGuardarUsuario);
            }
            if ((this.onGuardarUsuarioCompletedDelegate == null)) {
                this.onGuardarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGuardarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginGuardarUsuarioDelegate, new object[] {
                        usuarioDto}, this.onEndGuardarUsuarioDelegate, this.onGuardarUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.UsuariosServiceReference.IUsuarioService.BeginEditarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditarUsuario(usuarioDto, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ControlDeEstudio.UsuariosServiceReference.UsuariosDTO ControlDeEstudio.UsuariosServiceReference.IUsuarioService.EndEditarUsuario(System.IAsyncResult result) {
            return base.Channel.EndEditarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginEditarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto = ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(inValues[0]));
            return ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).BeginEditarUsuario(usuarioDto, callback, asyncState);
        }
        
        private object[] OnEndEditarUsuario(System.IAsyncResult result) {
            ControlDeEstudio.UsuariosServiceReference.UsuariosDTO retVal = ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).EndEditarUsuario(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEditarUsuarioCompleted(object state) {
            if ((this.EditarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditarUsuarioCompleted(this, new EditarUsuarioCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditarUsuarioAsync(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto) {
            this.EditarUsuarioAsync(usuarioDto, null);
        }
        
        public void EditarUsuarioAsync(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, object userState) {
            if ((this.onBeginEditarUsuarioDelegate == null)) {
                this.onBeginEditarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginEditarUsuario);
            }
            if ((this.onEndEditarUsuarioDelegate == null)) {
                this.onEndEditarUsuarioDelegate = new EndOperationDelegate(this.OnEndEditarUsuario);
            }
            if ((this.onEditarUsuarioCompletedDelegate == null)) {
                this.onEditarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginEditarUsuarioDelegate, new object[] {
                        usuarioDto}, this.onEndEditarUsuarioDelegate, this.onEditarUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.UsuariosServiceReference.IUsuarioService.BeginEliminarUsuario(string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEliminarUsuario(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ControlDeEstudio.UsuariosServiceReference.IUsuarioService.EndEliminarUsuario(System.IAsyncResult result) {
            base.Channel.EndEliminarUsuario(result);
        }
        
        private System.IAsyncResult OnBeginEliminarUsuario(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id = ((string)(inValues[0]));
            return ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).BeginEliminarUsuario(Id, callback, asyncState);
        }
        
        private object[] OnEndEliminarUsuario(System.IAsyncResult result) {
            ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).EndEliminarUsuario(result);
            return null;
        }
        
        private void OnEliminarUsuarioCompleted(object state) {
            if ((this.EliminarUsuarioCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EliminarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EliminarUsuarioAsync(string Id) {
            this.EliminarUsuarioAsync(Id, null);
        }
        
        public void EliminarUsuarioAsync(string Id, object userState) {
            if ((this.onBeginEliminarUsuarioDelegate == null)) {
                this.onBeginEliminarUsuarioDelegate = new BeginOperationDelegate(this.OnBeginEliminarUsuario);
            }
            if ((this.onEndEliminarUsuarioDelegate == null)) {
                this.onEndEliminarUsuarioDelegate = new EndOperationDelegate(this.OnEndEliminarUsuario);
            }
            if ((this.onEliminarUsuarioCompletedDelegate == null)) {
                this.onEliminarUsuarioCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEliminarUsuarioCompleted);
            }
            base.InvokeAsync(this.onBeginEliminarUsuarioDelegate, new object[] {
                        Id}, this.onEndEliminarUsuarioDelegate, this.onEliminarUsuarioCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ControlDeEstudio.UsuariosServiceReference.IUsuarioService.BeginObtenerUsuarios(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginObtenerUsuarios(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> ControlDeEstudio.UsuariosServiceReference.IUsuarioService.EndObtenerUsuarios(System.IAsyncResult result) {
            return base.Channel.EndObtenerUsuarios(result);
        }
        
        private System.IAsyncResult OnBeginObtenerUsuarios(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).BeginObtenerUsuarios(callback, asyncState);
        }
        
        private object[] OnEndObtenerUsuarios(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> retVal = ((ControlDeEstudio.UsuariosServiceReference.IUsuarioService)(this)).EndObtenerUsuarios(result);
            return new object[] {
                    retVal};
        }
        
        private void OnObtenerUsuariosCompleted(object state) {
            if ((this.ObtenerUsuariosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ObtenerUsuariosCompleted(this, new ObtenerUsuariosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ObtenerUsuariosAsync() {
            this.ObtenerUsuariosAsync(null);
        }
        
        public void ObtenerUsuariosAsync(object userState) {
            if ((this.onBeginObtenerUsuariosDelegate == null)) {
                this.onBeginObtenerUsuariosDelegate = new BeginOperationDelegate(this.OnBeginObtenerUsuarios);
            }
            if ((this.onEndObtenerUsuariosDelegate == null)) {
                this.onEndObtenerUsuariosDelegate = new EndOperationDelegate(this.OnEndObtenerUsuarios);
            }
            if ((this.onObtenerUsuariosCompletedDelegate == null)) {
                this.onObtenerUsuariosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnObtenerUsuariosCompleted);
            }
            base.InvokeAsync(this.onBeginObtenerUsuariosDelegate, null, this.onEndObtenerUsuariosDelegate, this.onObtenerUsuariosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ControlDeEstudio.UsuariosServiceReference.IUsuarioService CreateChannel() {
            return new UsuarioServiceClientChannel(this);
        }
        
        private class UsuarioServiceClientChannel : ChannelBase<ControlDeEstudio.UsuariosServiceReference.IUsuarioService>, ControlDeEstudio.UsuariosServiceReference.IUsuarioService {
            
            public UsuarioServiceClientChannel(System.ServiceModel.ClientBase<ControlDeEstudio.UsuariosServiceReference.IUsuarioService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BeginGuardarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = usuarioDto;
                System.IAsyncResult _result = base.BeginInvoke("GuardarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public ControlDeEstudio.UsuariosServiceReference.UsuariosDTO EndGuardarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                ControlDeEstudio.UsuariosServiceReference.UsuariosDTO _result = ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(base.EndInvoke("GuardarUsuario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEditarUsuario(ControlDeEstudio.UsuariosServiceReference.UsuariosDTO usuarioDto, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = usuarioDto;
                System.IAsyncResult _result = base.BeginInvoke("EditarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public ControlDeEstudio.UsuariosServiceReference.UsuariosDTO EndEditarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                ControlDeEstudio.UsuariosServiceReference.UsuariosDTO _result = ((ControlDeEstudio.UsuariosServiceReference.UsuariosDTO)(base.EndInvoke("EditarUsuario", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEliminarUsuario(string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("EliminarUsuario", _args, callback, asyncState);
                return _result;
            }
            
            public void EndEliminarUsuario(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("EliminarUsuario", _args, result);
            }
            
            public System.IAsyncResult BeginObtenerUsuarios(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ObtenerUsuarios", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> EndObtenerUsuarios(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ControlDeEstudio.UsuariosServiceReference.UsuariosDTO>)(base.EndInvoke("ObtenerUsuarios", _args, result)));
                return _result;
            }
        }
    }
}
